name: Build Game

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build the Game
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache Unity Library Folder
      - name: Cache Library
        uses: actions/cache@v4 # Upgraded to v4 to match actions standard
        with:
          path: Library
          key: Library-WebGL-${{ hashFiles('Packages/manifest.json', 'ProjectSettings/ProjectVersion.txt') }}
          restore-keys: |
            Library-WebGL-
            Library-

      # Build
      - name: Build 
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          versioning: Semantic # Or None if you don't want GameCI tracking versioning
          allowDirtyBuild: true # Prevents the "Branch is dirty" error block

      # Output
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build
